# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "* * * * *"   # 매일 9시 실행

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 5
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser
        
    - name: Run Update Python Script
      run: |
        python main.py
    - name: Update ReadMe.md file
      run: |
        git pull
        git add .
        git diff
        git config --local user.email "star7sss@naver.com"
        git config --local user.name "jangThang"
        git commit -m "Update README.md"
        git push origin +master
